import Header from "./components/Header";
import { hind_siliguri } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={hind_siliguri.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
